name: Deploy to Google Play Store

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Install Fastlane
        run:
          gem install fastlane

          # Setup Fastlane Plugins
      - name: Add Fastlane Plugins
        run: |
          fastlane add_plugin increment_version_code
          fastlane add_plugin increment_version_name
          fastlane add_plugin get_version_name

      - name: Deploy to Google Play Store
        run: |
          npm android:fastlane:beta
