name: PR - Testes com Jest
on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn
      - run: yarn test
